version: '3'
services:
  node1:
    image: ethereum/client-go
    volumes:
      - ./node1:/root/.ethereum
      - ./genesis.json:/genesis.json
    networks:
      - eth-net
    ports:
      - 8545:8545
    command: >
      --networkid 1234
      --nodiscover
      --maxpeers 0
      --http
      --http.addr "0.0.0.0"
      --http.port 8545
      --http.corsdomain "*"
      --http.api "eth,net,web3,personal"
      init /genesis.json

  node2:
    image: ethereum/client-go
    volumes:
      - ./node2:/root/.ethereum
      - ./genesis.json:/genesis.json
    networks:
      - eth-net
    ports:
      - 8546:8545
    command: >
      --networkid 1234
      --nodiscover
      --maxpeers 0
      --http
      --http.addr "0.0.0.0"
      --http.port 8545
      --http.corsdomain "*"
      --http.api "eth,net,web3,personal"
      init /genesis.json

  node3:
    image: ethereum/client-go
    volumes:
      - ./node3:/root/.ethereum
      - ./genesis.json:/genesis.json
    networks:
      - eth-net
    ports:
      - 8547:8545
    command: >
      --networkid 1234
      --nodiscover
      --maxpeers 0
      --http
      --http.addr "0.0.0.0"
      --http.port 8545
      --http.corsdomain "*"
      --http.api "eth,net,web3,personal"
      init /genesis.json

networks:
  eth-net: